viamrobotics/agent

subsystems/viamagent/viamagent.go

Thanks @abe-winter  for trying on your laptop. I was able to reproduce it on a new flashed rpi image. \
And tested the fix by running the custom `sudo /tmp/viam-agent-custom-aarch64 --install` 
```
2024-05-28T09:46:48.164-0400	INFO	viam-agent	viamagent/viamagent.go:129	adding a symlink to /tmp/viam-agent-custom-aarch64 at /opt/viam/bin/viam-agent
2024-05-28T09:46:48.171-0400	INFO	viam-agent	viamagent/viamagent.go:148	writing systemd service file to /usr/local/lib/systemd/system/viam-agent.service
2024-05-28T09:46:48.171-0400	INFO	viam-agent	viamagent/viamagent.go:163	enabling systemd viam-agent service
2024-05-28T09:46:48.792-0400	INFO	viam-agent	viamagent/viamagent.go:185	Install complete. Please (re)start the service with 'systemctl restart viam-agent' when ready.
```
[agent …

[APP-5068] fix agent install issue with service file

---

cmd/viam-agent/main.go
go.mod
subsystems/viamserver/viamserver.go

- make the start timeout for the viam-server subsystem configurable
- incidental -- expand VIAM_AGENT_DEVMODE to include running as non-root. (convenience feature for local testing)
On slow connections and with large binaries, the default 5 minute timeout isn't enough to download viam-server and modules.
(attributes.start_timeout is the new part)
```json
{
"agent": {
"viam-server": {
"release_channel": "stable",
"pin_version": "",
"pin_url": "",
"attributes": {"start_timeout": "1h"},
"disable_subsystem": false
}
},
"components": [
```
Tested on my local machine with the new config value missing and present. When present it logs as expected:
> 2024-08-28T15:12:44.807Z DEBUG   viam-agent      viamserver/viamserver.go:91     parsed duration 10m0s from key start_timeout

configurable `startTimeout` for viam-server subsystem

---

cmd/viam-agent/main.go

Move `VIAM_AGENT_DEVMODE` variable to the `opts` struct parsed by go-flags.
Visibility / consistency
```sh
$ go run ./cmd/viam-agent/ -h
Usage:
viam-agent runs as a background service and manages updates and the process lifecycle for viam-server.
Application Options:
-c, --config=   Path to config file (default: /etc/viam.json)
-d, --debug     Enable debug logging (for agent only) [$VIAM_AGENT_DEBUG]
-f, --fast      Enable fast start mode [$VIAM_AGENT_FAST_START]
-h, --help      Show this help message
-v, --version   Show version
--install   Install systemd service
--dev-mode  Allow non-root and non-service [$VIAM_AGENT_DEVMODE]
```

consume _DEVMODE var through opts

---

go.mod
go.sum
subsystems/provisioning/networkstate.go
subsystems/provisioning/provisioning.go
subsystems/syscfg/syscfg.go

There was a double mutex  lock introduced in 0.9.0 when configuration included the "networks" section of attributes.
This also includes two small fixes here for post 0.9.0 annoyances and bugs:
1. Reduces logging for missing primarySSID to one occurance.
2. Cleanly disabled provisioning when networkmanager is unavailable (or too old.) Basically prevents noisy, repeated failures on bullseye if/when people refused the NetworkManager upgrade during install.

[APP-6748] Fix deadlock when adding additional networks

---

subsystems/provisioning/generators.go
subsystems/provisioning/networkmanager.go
subsystems/provisioning/provisioning.go

* Make network gateway "optional" as there are cases where it may not be needed (local network)
* Add debug log line with parsed network settings
* Skip activating connection if error to add or update

Fix network settings error when gateway empty

---

subsystems/provisioning/definitions.go
subsystems/provisioning/grpc.go
subsystems/provisioning/networkmanager.go
subsystems/provisioning/portal.go
subsystems/provisioning/provisioning.go
subsystems/provisioning/scanning.go
subsystems/provisioning/setup.go

Doing a PR to Ale's branch for discussion. Needs to merge before that (#43) merges.
Tested on my Pi 5 and it works as expected. Only "catch" now is that if powersave is set explicitly, then the setting is removed entirely, the last remaining state "remains" until the next reboot (as the driver itself initially turned on powersave during boot.) That is, assuming the user hasn't manually configured their own setting.

Reactivate connection on powersave change, misc cleanup.

---

go.mod
go.sum
subsystems/provisioning/provisioning.go
subsystems/provisioning/setup.go
utils.go

This fixes two cases... the first, in the bug, is when the wifi is blocked by rfkill (aka, "airplane mode".) This has recently (past week) become the default for new Raspberry Pi image installs unless the user specifically adds a wifi network during the image creation process.
The second case is for devices that have no wifi adapters at all. Previously, results were undefined, and provisioning would continue trying to execute, scan, start hotspots, etc. even if that wasn't possible. Now the lack of wifi hardware causes provisioning to self-disable until the next restart of agent.

[APP-7026] Handle rfkill, no-wifi-device cases

---

subsystem.go
subsystems/viamserver/viamserver.go

Collected fixes from RC testing.

0.10.0-rc Collected Fixes

---

cmd/viam-agent/main.go
manager.go

- consume `debug` field from cloud config, instead of only from CLI switch
It's difficult to set this currently.
Where is the right place for this? I put it in the attributes for the viam-agent subsystem, but the `map[string]DeviceSubsystemConfig` approach seems less ergonomic post unification.
With debug set to true:
> 2024-12-04T08:51:22.774Z	INFO	viam-agent	viamserver/viamserver.go:183	viam-server started
> 2024-12-04T08:51:22.774Z	**DEBUG**	viam-agent	agent/manager.go:277	starting background checks
> 2024-12-04T08:51:22.774Z	**DEBUG**	viam-agent	agent/manager.go:185	Checking cloud for update
> 2024-12-04T08:51:22.882Z	INFO	rdk.package_manager	packages/deferred_package_manager.go:143	cloud package manager created asyncronously
With debug set to false (second restart):
> …

APP-6990 consume debug level from cloud config

---

cmd/viam-agent/main.go
subsystems/provisioning/definitions.go
subsystems/provisioning/generators.go
subsystems/provisioning/networkmanager.go
subsystems/provisioning/networkstate.go
subsystems/provisioning/provisioning.go
subsystems/provisioning/scanning.go
subsystems/provisioning/setup.go

Wifi networks found from scan were associated with the scanning interface (e.g. wlan0) but externally configured wifi settings (e.g. prexisting networks) might not be associated with a specific interface. Thus, duplicate networks (one for "any" and one for "wlan0" were causing issues.
This PR should deduplicate the two maps. If a connection/settings has no interface associated (and it's wifi) it gets handled as though it WAS associated with the current HotspotInterface (can be configured, otherwise first detected wifi adapter.)

Fix wifi candidate selection to include non-interface-bound candidates

---

subsystems/provisioning/networkmanager.go

This PR skips the process initiated in the "background loop" when MDNS mode is enabled - as done [here](https://github.com/viamrobotics/agent/blob/aw-mdns-provision/subsystems/provisioning/provisioning.go#L149).

[AW-MDNS-Provision] Skip Background Loop 

---

install.sh
subsystems/provisioning/definitions.go
subsystems/provisioning/networkmanager.go
subsystems/provisioning/networkstate.go
subsystems/provisioning/provisioning.go
subsystems/provisioning/scanning.go
subsystems/provisioning/setup.go

EDIT: rc2 replaces rc1. Fix a timeout issue that caused erratic behavior on "normal" (read, previously fully working) systems.
EDIT: rc1 replaces rc0. Minor fix for unrelated reboot timeout code.
Two main changes...
1. If NM older than 1.38, avoid using RadioFlags to disable when wifi hardware is absent, and rely on later device scan.
2. Modify wifi scanning to detect repeated failures when in hotspot mode, and (after 3) disable such scans after warning the user. This means the network list in the web portal or provided to the mobile app may be several minutes out of date, as scan data had to come from before the hotspot was started. May want to advise users to reduce the fallback timeout to a lower interval if this causes them problems. Otherwise we hang out in hotspot for 10 minutes, …

[APP-7257] Support older NM (>1.30.0) and hardware that cannot scan in hotspot mode

---

cmd/viam-agent/main.go
manager.go
subsystems/provisioning/templates/index.html
subsystems/viamagent/viamagent.go
subsystems/viamserver/viamserver.go

Quick PR for easy fixes.
Needs testing for the linked Jira issues
1. Install
2. Upgrade/downgrade viam-agent and ensure a "disabled" systemd service remains disabled after upgrade.
3. Confirm captive portal works for new wifi (mainly that browser doesn't throw errors) and fixes capitalization issue.
4. Corrupt /etc/viam.json, ensure errors are clear and file is renamed
5. Make sure it runs okay for a while (15+ minutes) with the new, shorter timeout.
6. Kill viam-server (or otherwise make it fail) and confirm it logs and restarts quickly.

[APP-7364] [APP-7366] [RSDK-9684] [APP-7154] Add more logging, reduce monitoring loop time, misc small fixes.

---

.github/workflows/test.yaml
.gitignore
Makefile
utils/config_test.go

This automates builds/publishing for both merges to main ("dev" releases) AND stable releases (directly triggered by creating a release in GH.)

[RSDK-7007] Add prerelease and other build automation

---

.github/workflows/workflow.yaml
subsystems/networking/networkmanager.go

Tiny fix, handle the case where an underlying connection has been deleted from networkmanager while running. Fix incidental lock (lack of) usage as well.

Let addOrUpdateConnection() handle live connection deletion

---

dev-version.sh

Same fix as RDK, even though we don't have -rc tags here currently.

[APP-7829] Fix dev-version.sh to handle -rc and other tag sorting

---

cmd/provisioning-client/bluetooth.go
cmd/provisioning-client/grpc.go
cmd/provisioning-client/main.go
cmd/provisioning-client/opts.go
go.mod
go.sum
manager.go
subsystems/networking/bluetooth_characteristics_linux.go
subsystems/networking/bluetooth_linux.go
subsystems/networking/definitions_linux.go
subsystems/networking/networking_linux.go
subsystems/networking/networkmanager_linux.go
utils/config.go

Update 03-28: I believe this is now feature complete. I've added full bluetooth functionality to cmd/provisioning-client and validated it works at least linux->linux.
Set the following in the agent version control:
EDIT: Updated to ble.3 rev as of 03-28 afternoon
Added encryption for all client>device writes, using rsa.OAEP, and encoding the public key with x509 PKIX (ASN.1 DER)
```
"agent": "http://packages.viam.com/temp/viam-agent-v0.16.0-ble.3-aarch64"
```
Outstanding issues:
* ~Automatic pairing: Not working on Android, may not be required at all, need to investigate further. Removed for now.~
* ~Advertised device name may conflict with OS settings for device.~
Update: Both of the above issues were resolved by adding code to disable ReverseDiscovery in the host's bluetooth config. …

[APP-7889][APP-7791][APP-7636][APP-7946] Bluetooth Provisioning

---

subsystems/viamserver/viamserver.go
utils/utils.go

General cleanup and bug fixes for windows. Fixes red-herring bugs enumerated in title (mostly all related to something that was accidentally broken by a bad rebase, but actually DO work, so removing the windows-specific bypass logic.) ALSO fixes the use of "file:///" version control URLs on windows.

[RSDK-10343][RSDK-10341][RSDK-10342] Windows Fixes

---

subsystems/viamserver/viamserver.go
utils/config.go

- ignore missing checkURL in HealthCheck when GOOS=windows
- always allow restart on windows
- shorten default startup timeout on windows (for user convenience so upgrades show up promptly, because we will always hit the timeout)
Otherwise agent will stop RDK when `ViamServerStartTimeoutMinutes` hits (see logs below).
Note: the matchinglogger *does* find checkURL when you run the agent from cmd.exe. This only fails in service mode. Not sure why, needs follow-up work.
To see this in prod, toggle between 0.16.1-dev.10 (behaves) and dev.11 (restarts when healthcheck fails).
Example of health check / restart behavior
> 4/10/2025, 10:16:54 PM info rdk   server/entrypoint.go:96   Viam RDK   version 0.70.0  git_rev xxxxxx
4/10/2025, 10:16:53 PM info viam-agent   viamserver/viamserver.go:89   …

ignore healthcheck failure on windows

---

version_control.go

- on windows only, detect the UnpackedPath="" case and replace with DlPath
Protect against download looping
Guessing this case comes about because UnpackedPath is a local-only field; it doesn't get set when version_cache.json is written after a recoverable error. (Have not confirmed this yet and may be misunderstanding the origin of the problem).
- I edited the version_cache.json on my local machine to have UnpackedPath=""
- as expected, agent went into a download loop trying to update rdk
- I made this code change; it prevented the loop

tolerate blank UnpackedPath case on windows

---

utils/testutils.go
utils/utils_test.go

- add MockViamDirs and Touch testutils
- add basic tests for DecompressFile, GetFileSum, CheckIfSame, ForceSymlink, WriteFileIfNew
test coverage

test some utils

---

version_control.go
version_control_test.go

- add basic test for the `UpdateBinary`
- (incidental) moved up the blank `UnpackedPath` fix to cover symlink creation
Increase test coverage

test UpdateBinary

---

subsystems/networking/connstate_linux.go
subsystems/networking/definitions_linux.go
subsystems/networking/networkmanager_linux.go
subsystems/networking/scanning_linux.go

This fixes two subtle but ugly bugs. The first was that provisioning wouldn't always exit right away when new wifi was added. The second is that if a bluetooth tethering connection is present (but not working, e.g. disabled on phone that's paired) limit the connection attempts to the visibility timeout (one minute.)
Test build: https://storage.googleapis.com/packages.viam.com/temp/viam-agent-v0.18.0-rc1-aarch64

Allow provisioning mode to exit quickly when new wifi is added, fix bluetooth tethering retry rate.

---

subsystems/networking/bluetooth_linux.go
subsystems/networking/networking_linux.go
subsystems/networking/networkmanager_linux.go
subsystems/syscfg/syscfg_linux.go

Guard some BT code chunks with checks for BT being disabled. Also fixes the repeated healthcheck failures for syscfg. (One-liner.)

[APP-8147] [APP-8150] Fix syscfg healthcheck failures, add BT disabled checks around BT code

---

cmd/viam-agent/main_windows.go
manager.go
subsystems/viamserver/viamserver.go
utils/logger.go
utils/utils.go
utils/utils_linux.go
utils/utils_windows.go
version_control.go

This fixes the startup and health checks for viam server by no longer writing to the (non-existant) STDOUT when in windows service mode. It also allocates a console, allowing interrupt signaling for graceful shutdown of viam-server. Lastly, it improves handling/adding the ".exe" suffix for windows. Appending it immediately upon reception from the cloud, rather than manipulating it multiple places later.

[APP-8059] [APP-7835] Improve windows service functionality

---

agent.go
cmd/viam-agent/main.go
cmd/viam-agent/main_linux.go
cmd/viam-agent/main_windows.go
manager.go
subsystems/viamserver/viamserver.go

Note: This should merge after #108 and until then, will look like a larger set of changes.
This update makes viam-agent exit gracefully after it has installed a new update for itself (and optionally viam-server) when it's safe to do so. That is, when viam-server is disabled, or reports "safe to restart."
This also fixes a bug on windows preventing lockups or "self-exit" there from working as intended.

[APP-7500] [RSDK-10333] Automatically restart agent when update available (and safe)

---

manager.go
subsystems/viamserver/viamserver.go
version_control.go

Note: Should merge after #109 as this inherits those changes and looks like bigger change set until then
This adds a CleanCache() function which prunes the cache and removes any obsolete/stray files to recover disk space. It runs every 24 hours, but won't run within the first 15 minutes of startup to avoid adding load on machines that may have been offline for an extended period and have a lot of updates to get through.

[RSDK-9293] Automatically prune cached binaries

---

agent.go
cmd/viam-agent/main.go
manager.go
subsystems/networking/bluetooth_linux.go
subsystems/networking/networking_linux.go
subsystems/networking/networkmanager_linux.go
subsystems/networking/setup_linux.go
utils/config.go
utils/config_old.go
utils/config_test.go

Due to the way Agent stacks configs (e.g. including built-in defaults, then processing viam-defaults.json, before finally using values from the cloud) booleans set to true at a lower level (viam-defaults) cannot be overridden with false at higher layers, as "false" is the same as unset due to json marshalling using "omitempty."
This adds a new Tribool type that allows for an explicitly "unset" value, subsequently allowing this kind of optional override.
Tested manually with various combinations of setting debug in viam-defaults, CLI (always takes precedence) and cloud. Appears to work, but as this touches a LOT of places, may not be urgent to get in.

[APP-8238] Convert all boolean values in config to new Tribool type

---

subsystems/viamserver/viamserver.go

This is kinda quick and dirty... should really dedupe isRestartAllowed() and HealthCheck() as they do a LOT of the same stuff. But for now, it solves the problem I believe.

Make agent try all local IPs for healthchecks

---

.github/workflows/build-windows-installer.yaml

- changed `runs-on: windows-2019` to `windows-2022` in actions YML
Github is [deprecating the windows-2019 runner](https://github.com/actions/runner-images/issues/12045).
- actions run [here](https://github.com/viamrobotics/agent/actions/runs/15424388113)
- I tested that ^ build on an old OS version and it worked

APP-8440 move installer build to windows-2022

---

subsystems/viamserver/viamserver.go

should remove restarts on false positives and stop hiding issues with the viam-server if it is indeed unresponsive.

RSDK-10985 - Remove viam-server healthcheck

---

utils/config.go

side steps the whole only validate config if it is different from previous, but didn't think we needed to do that yet
the idea is that we would only warn if this is a deliberate choice that the user made, but also down to just remove the log entirely

RSDK-11021 - Only log ssid truncated if it is user defined

---

cmd/provisioning-client/bluetooth.go
cmd/provisioning-client/opts.go
examples/agent-config.jsonc
subsystems/networking/bluetooth_characteristics_linux.go
subsystems/networking/bluetooth_linux.go
subsystems/networking/bluetooth_tethering_linux.go
subsystems/networking/definitions.go
subsystems/networking/definitions_linux.go
subsystems/networking/generators_linux.go
subsystems/networking/grpc_linux.go
subsystems/networking/networking_linux.go
subsystems/networking/networkmanager_linux.go
subsystems/networking/networkstate_linux.go
subsystems/networking/portal_linux.go
subsystems/networking/scanning_linux.go
subsystems/networking/setup_linux.go
subsystems/viamserver/viamserver.go
utils/config.go
utils/config_test.go

Should be feature complete!
UPDATE 07/22/2025: Rev4 is now built and released.
UPDATE 07/17/2025: Rev3 is now built and released. This fixes some bugs due to inconsistencies in network naming.
UPDATE 07/11/2025: Rev2 has moved to using the "unlock_pairing" characteristic, as iOS and android no longer expose the local BT Hardware Address to applications. Writing a "1" (string) to the characteristic temporarily enables pairing from any device, and lasts for the duration the device is in provisioning mode.
Test build here: http://packages.viam.com/temp/viam-agent-tethering.rev4-aarch64
Tethering works almost entirely based on pairing from the phone to the device, the only issue is establishing "trust" before the pairing, which can be established three ways:
~~1. The mobile app should write …

[RSDK-10815] [APP-8673] Bluetooth Tethering

---

subsystems/networking/connstate_linux.go
subsystems/networking/networkmanager_linux.go
subsystems/networking/networkmanager_linux_test.go

This looks for a touchfile at `/opt/viam/etc/force_provisioning_mode` and if found, enters provisioning mode until a user submits data (and calls ExitProvisioning()) OR the normal `retry_connection_timeout_minutes` limit (default 10 minutes) expires.
This is meant to be used by external scripts that could be tied to a "pair" button or similar.

[APP-8655] Force Provisioning Mode

---

subsystems/networking/bluetooth_characteristics_linux.go
subsystems/networking/generators_linux.go
subsystems/networking/networkmanager_linux.go

Test binary: http://packages.viam.com/temp/viam-agent-v0.21.0+tetherfixes.1-aarch64
This adds `ipv4.never-default=true` to the hotspot settings. This is needed because otherwise this is considered an active network, and if it can't reach the internet (which it typically never can) it causes NM connectivity checks to report it as "limited access." This was never a problem previously because we were never expecting to be online while in hotspot mode, but now with bluetooth tethering, that is possible.
This also has two VERY minor fixes, one for a typo Warn()>Warnf(), and another to mark a tried network slightly earlier in case of early return.

Update hotspot IP settings to never be the default route

---

go.mod
go.sum
subsystems/networking/definitions_linux.go
subsystems/networking/generators_linux.go
subsystems/networking/networking_linux.go
subsystems/networking/networkmanager_linux.go
subsystems/networking/networkstate_linux.go
subsystems/networking/scanning_linux.go
subsystems/networking/setup_linux.go

Moved my personal fork of the GoNetworkManager library to the Viam org. This updates the references in agent to use the new location.

Switch GNM to viamrobotics repo

---

manager.go

[RSDK-11890](https://viam.atlassian.net/browse/RSDK-11890)
I do not think this bug was fully responsible for the ~3.5 mins it took for `viam-server` to come online in the case that NetworkManager had no active connection. That was [RSDK-11947](https://viam.atlassian.net/browse/RSDK-11947) (PR forthcoming). It did, however, exacerbate the situation by cutting off the networking subsystem early from completing its attempt to activate an available WiFi connection.
[RSDK-11947]: https://viam.atlassian.net/browse/RSDK-11947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RSDK-11890]: https://viam.atlassian.net/browse/RSDK-11890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-11890 Avoid immediate HealthCheck timeout when Start takes longer than 15s

---

agent.go
cmd/viam-agent/main.go
subsystems/networking/networkmanager_linux.go
subsystems/networking/networkmanager_linux_test.go
subsystems/viamserver/viamserver.go
utils/config.go
utils/testutils.go
utils/utils.go
utils/utils_test.go
version_control.go
version_control_test.go

Agent uses a global map at `utils.ViamDirs` to track information about where it keeps files on disk. A map seems to have been chosen to allow iteration over the list of directories but comes with the tradeoff of not being discoverable by autocomplete and being vulnerable to an (admittedly unlikely) set of logic errors if a typo in a key makes it through testing and code review. This PR changes `utils.ViamDirs` to be a struct with members for each of the keys that were previously in the map. Reflection is used to continue supporting the one code path that relied on iterating over the map values and two tests that programmatically set the values to temporary test directories.

Change ViamDirs from map to struct
